name: GoluNav Docker Compacket

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set Version With Timestamp
      id: set_version
      run: echo "VERSION=$(date +%s)" >> $GITHUB_ENV
      
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with: 
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Build The Docker Image
      run: docker build . --file Dockerfile --tag goolucky/golu-nav:${{ env.VERSION }}

    - name: Tag Image As Latest
      run: docker tag goolucky/golu-nav:${{ env.VERSION }} goolucky/golu-nav:latest

    - name: Push Docker Image With Timestamp Tag
      run: docker push goolucky/golu-nav:${{ env.VERSION }}

    - name: Push Docker Image With Latest Tag
      run: docker push goolucky/golu-nav:latest
      
